export function renderSkills() {
  return `
    <section class="section skills" id="competences">
      <div class="container">
        <h2 class="section-title">Mes <span>Services</span></h2>
        
        <!-- Services Grid -->
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 mb-20">
          <div class="group cursor-pointer">
            <div class="flex items-start gap-4">
              <div class="w-16 h-16 rounded-lg bg-gradient-to-br from-primary/20 to-primary/5 flex items-center justify-center text-2xl text-primary group-hover:shadow-lg group-hover:from-primary/30 transition-all duration-300 flex-shrink-0">
                <i class="fas fa-paint-brush"></i>
              </div>
              <div>
                <h3 class="font-semibold text-gray-900 text-lg mb-2">Graphic Design</h3>
                <p class="text-gray-600 text-sm leading-relaxed">Création de visuels impactants qui allient esthétique et stratégie.</p>
              </div>
            </div>
          </div>
          
          <div class="group cursor-pointer">
            <div class="flex items-start gap-4">
              <div class="w-16 h-16 rounded-lg bg-gradient-to-br from-cyan-500/20 to-cyan-500/5 flex items-center justify-center text-2xl text-cyan-500 group-hover:shadow-lg group-hover:from-cyan-500/30 transition-all duration-300 flex-shrink-0">
                <i class="fas fa-pen-fancy"></i>
              </div>
              <div>
                <h3 class="font-semibold text-gray-900 text-lg mb-2">Logo Design</h3>
                <p class="text-gray-600 text-sm leading-relaxed">Logos uniques et mémorables, pensés pour durer.</p>
              </div>
            </div>
          </div>
          
          <div class="group cursor-pointer">
            <div class="flex items-start gap-4">
              <div class="w-16 h-16 rounded-lg bg-gradient-to-br from-violet-500/20 to-violet-500/5 flex items-center justify-center text-2xl text-violet-500 group-hover:shadow-lg group-hover:from-violet-500/30 transition-all duration-300 flex-shrink-0">
                <i class="fas fa-cube"></i>
              </div>
              <div>
                <h3 class="font-semibold text-gray-900 text-lg mb-2">Branding</h3>
                <p class="text-gray-600 text-sm leading-relaxed">Identités visuelles cohérentes qui donnent une personnalité forte à votre marque.</p>
              </div>
            </div>
          </div>
          
          <div class="group cursor-pointer">
            <div class="flex items-start gap-4">
              <div class="w-16 h-16 rounded-lg bg-gradient-to-br from-green-500/20 to-green-500/5 flex items-center justify-center text-2xl text-green-500 group-hover:shadow-lg group-hover:from-green-500/30 transition-all duration-300 flex-shrink-0">
                <i class="fas fa-graduation-cap"></i>
              </div>
              <div>
                <h3 class="font-semibold text-gray-900 text-lg mb-2">Formation</h3>
                <p class="text-gray-600 text-sm leading-relaxed">Ateliers pratiques pour apprendre et maîtriser les outils du design.</p>
              </div>
            </div>
          </div>
        </div>
        
        <!-- Tools Section -->
        <div>
          <div class="flex items-center justify-between mb-8">
            <div>
              <h3 class="text-2xl lg:text-3xl font-bold text-gray-900 mb-2">Outils & Partenaires</h3>
              <p class="text-gray-600">Les outils et technologies que j'utilise pour donner vie à mes créations</p>
            </div>
            <button id="viewAllToolsBtn" class="hidden md:flex items-center gap-2 px-6 py-3 rounded-lg border border-gray-300 text-gray-700 font-medium hover:border-primary hover:text-primary hover:shadow-md transition-all duration-300 bg-white">
              <i class="fas fa-grid-2x2"></i>
              <span>Voir tout</span>
            </button>
          </div>
          
          <!-- Carousel avec scroll libre -->
          <div class="tools-carousel-wrapper overflow-x-auto scroll-smooth" id="toolsCarouselWrapper">
            <div class="tools-carousel flex gap-4 md:gap-6 pb-4" id="toolsCarousel">
              <!-- Tools will be generated by JavaScript -->
            </div>
          </div>

          <!-- Mobile "Voir tout" button -->
          <div class="md:hidden flex justify-center mt-4">
            <button id="viewAllToolsMobileBtn" class="flex items-center gap-2 px-6 py-2 rounded-lg border border-gray-300 text-gray-700 font-medium text-sm hover:border-primary hover:text-primary transition-all duration-300">
              <i class="fas fa-grid-2x2"></i>
              <span>Voir les 6 outils</span>
            </button>
          </div>
        </div>

        <!-- Modal "Voir tous" -->
        <div id="toolsModal" class="hidden fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4 backdrop-blur-sm">
          <div class="bg-white rounded-2xl shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">
            <!-- Modal Header -->
            <div class="sticky top-0 bg-white border-b border-gray-200 px-6 py-4 md:px-8 md:py-6 flex items-center justify-between">
              <h2 class="text-2xl font-bold text-gray-900">Tous les outils</h2>
              <button id="closeToolsModal" class="text-gray-500 hover:text-gray-700 text-2xl transition-colors">
                <i class="fas fa-times"></i>
              </button>
            </div>

            <!-- Modal Content -->
            <div class="p-6 md:p-8">
              <div class="grid grid-cols-2 md:grid-cols-3 gap-4 md:gap-6">
                <!-- Tools grid will be generated by JavaScript -->
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  `;
}

export function initSkills() {
  const tools = [
    {
      name: 'Inkscape',
      icon: 'https://cdn.brandfetch.io/id_evqohnj/theme/dark/logo.svg',
    },
    {
      name: 'Photopea',
      icon: 'https://cdn.brandfetch.io/idjom661t2/theme/dark/logo.svg',
    },
    {
      name: 'Canva',
      icon: 'https://cdn.brandfetch.io/id9mVQlyBl/w/400/h/400/theme/dark/icon.jpeg',
    },
    {
      name: 'Snapseed',
      icon: 'https://cdn.brandfetch.io/id9bEvVa-d/w/400/h/400/theme/dark/icon.jpeg',
    },
    { name: 'PixelLab', icon: 'assets/images/logos/pixellablogo.jpg' },
    {
      name: 'Capcut',
      icon: 'https://cdn.brandfetch.io/idUmqKFgE3/w/400/h/400/theme/dark/icon.jpeg',
    },
  ];

  const carousel = document.getElementById('toolsCarousel');
  const carouselWrapper = document.getElementById('toolsCarouselWrapper');
  const modal = document.getElementById('toolsModal');
  const viewAllBtn = document.getElementById('viewAllToolsBtn');
  const viewAllMobileBtn = document.getElementById('viewAllToolsMobileBtn');
  const closeModalBtn = document.getElementById('closeToolsModal');
  const isMobile = window.innerWidth < 768;

  if (!carousel || !carouselWrapper) return;

  // Créer un élément tool réutilisable
  const createToolElement = (tool, inModal = false) => {
    const div = document.createElement('div');

    if (inModal) {
      // Version pour la modale (grille)
      div.className =
        'flex flex-col items-center gap-3 p-4 rounded-lg  hover:border-primary hover:shadow-lg transition-all duration-300';
    } else {
      // Version pour le carousel (horizontal)
      div.className =
        'tool-item flex-shrink-0 flex items-center gap-3 px-5 py-3 rounded-lg hover:border-primary hover:shadow-md transition-all duration-300 min-w-max hover:scale-105';
    }

    if (inModal) {
      div.innerHTML = `
        <img src="${tool.icon}" alt="${tool.name}" class="h-12 w-12 object-contain" onerror="this.style.opacity='0.5'" loading="lazy" />
        <span class="font-medium text-gray-700 text-center text-sm">${tool.name}</span>
      `;
    } else {
      div.innerHTML = `
        <img src="${tool.icon}" alt="${tool.name}" class="h-9 w-9 object-contain flex-shrink-0" onerror="this.style.opacity='0.5'" loading="lazy" />
        <span class="font-medium text-gray-700 whitespace-nowrap">${tool.name}</span>
      `;
    }

    return div;
  };

  // Remplir le carousel (une seule copie pour le scroll libre)
  tools.forEach((tool) => {
    carousel.appendChild(createToolElement(tool, false));
  });

  // Ajouter l'animation auto-scroll uniquement sur desktop
  if (!isMobile) {
    carouselWrapper.classList.add('carousel-auto-scroll');
  } else {
    // Sur mobile, désactiver l'animation auto-scroll
    carousel.classList.remove('animate-scroll');
  }

  // Gérer la modale "Voir tout"
  const openModal = () => {
    modal.classList.remove('hidden');
    document.body.style.overflow = 'hidden';

    // Remplir la modale avec la grille des outils
    const modalGrid = modal.querySelector('.grid');
    modalGrid.innerHTML = '';
    tools.forEach((tool) => {
      modalGrid.appendChild(createToolElement(tool, true));
    });
  };

  const closeModal = () => {
    modal.classList.add('hidden');
    document.body.style.overflow = 'auto';
  };

  // Event listeners pour ouvrir la modale
  viewAllBtn?.addEventListener('click', openModal);
  viewAllMobileBtn?.addEventListener('click', openModal);
  closeModalBtn?.addEventListener('click', closeModal);

  // Fermer la modale en cliquant sur le backdrop
  modal?.addEventListener('click', (e) => {
    if (e.target === modal) {
      closeModal();
    }
  });

  // Fermer avec Escape
  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape' && !modal.classList.contains('hidden')) {
      closeModal();
    }
  });

  // Gérer le redimensionnement
  window.addEventListener('resize', () => {
    const newIsMobile = window.innerWidth < 768;
    if (newIsMobile && !isMobile) {
      // Passage de desktop à mobile
      carouselWrapper.classList.remove('carousel-auto-scroll');
      carousel.classList.remove('animate-scroll');
    } else if (!newIsMobile && isMobile) {
      // Passage de mobile à desktop
      carouselWrapper.classList.add('carousel-auto-scroll');
      carousel.classList.add('animate-scroll');
    }
  });
}
